Feature/tournament management and template edit
lejbron/arkenstone pull request #10
Opened 2021-04-10 14:52 UTC by Kneshal

Добавил view для открытия/закрытия регистрации, добавил декоратор для проверки пользователя, добавил шаблон-карточку турнира и т.д.

2021-04-11 07:59 UTC, lejbron requested changes

2021-04-11 07:59 UTC, lejbron commented on tournaments/models.py
> +        help_text='Укажите организатора турнира',
Ты на чем то основывался, когда первыми ставил verbose_name и help_text? 
Я просто думал о порядке перечисления параметров и так и не понял, чем руководствоваться)

2021-04-11 07:59 UTC, lejbron commented on tournaments/views/status_change_forms.py
> +    return check_user
Стоит все таки вынести в отдельный файл, а так же использовать wraps из functools, убирает некоторые внутренние проблемы использования - получение имени и документации. 

[Статья про декоратор](https://simpleisbetterthancomplex.com/2015/12/07/working-with-django-view-decorators.html)

Статья про functuls.wraps:
[eng](https://lerner.co.il/2019/05/05/making-your-python-decorators-even-better-with-functool-wraps/)
[rus](https://www.google.ru/amp/s/webdevblog.ru/ispolzovanie-functool-wraps-v-dekoratorah-python/amp/)

В целом решение огонь, самому даже в голову не приходило такое! 🔥

2021-04-11 07:59 UTC, lejbron commented on tournaments/forms.py
> +
по идее можно было просто добавить поле в список в Meta классе, а потом при создании формы во view задать значения, из которых можно выбирать.
Пример [тут](https://github.com/lejbron/arkenstone/blob/ef1e473d89cd2fb5a302db128014b112ca353a22/tournaments/views/data_input_forms.py#L72).

2021-04-11 07:59 UTC, lejbron commented on tournaments/templates/tournaments_list.html
> +  Открыть новый турнир
Думаю все таки Создать новый турнир, а не открыть.

2021-04-11 07:59 UTC, lejbron commented on tournaments/urls.py
> +    path('<slug:tt_slug>/close-registration/', views.close_registration, name='tournament-close-registration'),
В name можно сократить registration до reg.

2021-04-11 07:59 UTC, lejbron commented on tournaments/views/data_input_forms.py
> +        tournament.save()
Если добавить поле через Meta класс модели, достаточно будет просто сохранить форму.

2021-04-11 08:28 UTC, Kneshal commented on tournaments/models.py
> +        help_text='Укажите организатора турнира',
Просто привык так делать)

2021-04-11 08:29 UTC, Kneshal commented on tournaments/forms.py
> +
Попробую, также хотел сделать, но не нашел как.

2021-04-11 08:29 UTC, Kneshal commented on tournaments/templates/tournaments_list.html
> +  Открыть новый турнир
Поправлю

2021-04-11 09:37 UTC, Kneshal commented on tournaments/views/status_change_forms.py
> +    return check_user
Тут кстати еще предполагалось, что если прав нет, то редиректит на страницу 403.html. Надо бы ее добавить.

2021-04-11 09:55 UTC, lejbron commented on tournaments/views/status_change_forms.py
> +    return check_user
Страницу добавлю в mini_release тогда, когда все причесывать буду. Задачку сделаю, спасибо, что напомнил)

2021-04-11 10:06 UTC, lejbron commented on tournaments/views/status_change_forms.py
> +    return check_user
с декоратором есть проблема:
нельзя вызывать для [функций изменения статуса тура](https://github.com/lejbron/arkenstone/blob/7fc4922adb92fbdd7e8b50fcfa2202a5dcc4da16/tournaments/views/status_change_forms.py#L67) - вместо tt_slug приходит tour_slug

2021-04-12 07:14 UTC, lejbron commented on tournaments/decorators.py
> +            raise PermissionDenied
получается если мы придем сюда из else, то снова будет ошибка - ведь у нас tournament определяется только в if и elif. 
Думаю нужно закладываться на то, что в функциях, в которых нельзя получить турнир, этот декоратор применяться не должен. А значит пункт с else не нужен.

2021-04-12 07:23 UTC, Kneshal commented on tournaments/decorators.py
> +            raise PermissionDenied
Из else мы сюда не придем, там идет возврат к функции без изменений.

2021-04-12 07:27 UTC, lejbron commented on tournaments/decorators.py
> +            raise PermissionDenied
да, ты прав, не придем. 
Но тогда какой смысл в декораторе для такой функции? думаю лучше получать ошибки и понимать, что декоратор к функции не применим. 

т е предлагаю else все же убрать и использовать декоратор только для функций, в которых можно получить турнир и проверить орг ли пытается с ним что-то сделать.

2021-04-12 07:31 UTC, lejbron commented on tournaments/views/data_input_forms.py
> +    return redirect('index')
а зачем в рамках этой задачи трогать регистрацию? 
конструкция с if not очень непонятно читается.

2021-04-12 07:32 UTC, lejbron commented on tournaments/views/status_change_forms.py
> +        return redirect('tournaments-list')
нужно возвращать на страницу турнира, а не страницу со списком

2021-04-12 07:39 UTC, Kneshal commented on tournaments/decorators.py
> +            raise PermissionDenied
Наверное тогда для большей очевидности, сделать отдельные декораторы для турнира и тура.

2021-04-12 07:40 UTC, Kneshal commented on tournaments/views/data_input_forms.py
> +    return redirect('index')
Это мне ревьюер так просил делать в рамках практикума:)

2021-04-12 07:41 UTC, Kneshal commented on tournaments/views/status_change_forms.py
> +        return redirect('tournaments-list')
Ок

2021-04-12 07:54 UTC, Kneshal commented on tournaments/views/status_change_forms.py
> +        return redirect('tournaments-list')
Поправил до более правильной конструкции:    
`if (count % 2 == 0) or (count > 0):
        tournament.tt_status = 'creg'
        tournament.save()
    return redirect('tournament-detail', tournament.tt_slug)`

2021-04-12 07:59 UTC, Kneshal commented on tournaments/decorators.py
> +            raise PermissionDenied
Может тогда в else выбрасывать какое-нибудь исключение, например ObjectDoesNotExist

2021-04-12 08:04 UTC, Kneshal commented on tournaments/decorators.py
> +            raise PermissionDenied
Или SuspiciousOperation

2021-04-12 14:53 UTC, lejbron commented on tournaments/decorators.py
> +            raise PermissionDenied
думаю надо оставить один для турнира и тура, потом при необходимости добавить туда матч. 
можно повесить исключение на else, да - но по идее лучше чтобы в этот момент все просто ломалось - и мы понимали, что применяем этот декоратор не там, где нужно

2021-04-12 14:55 UTC, lejbron commented on tournaments/views/data_input_forms.py
> +    return redirect('index')
нет, я понял почему так - чтобы else не писать, сначала показалось странным. оставляем так!

2021-04-12 14:55 UTC, lejbron commented on tournaments/views/status_change_forms.py
> +        return redirect('tournaments-list')
только тут должно было быть and, а не or - но я уже поменял, когда модальное окно правил

2021-04-12 17:46 UTC, lejbron approved these changes
:fire:

2021-04-12 18:04 UTC, merged